### ISSUE TITLE
Lisp expression?

### ISSUE THREAD

**Issue by seemsindie** [zk-phi/symon#11]
When i run symon-mode, the prompt comes and asks for Lisp expression, why?

**Comment by zk-phi** [comment]
argument for function `read` is probably unexpectedly `nil`.
are you running `symon` on linux right ?

**Comment by seemsindie** [comment]
Yes on arch linux 64bit

**Comment by zk-phi** [comment]
thanks.
can you check that `-o` option for `free` command is supported on your system ?

**Comment by seemsindie** [comment]
╭─ivan@development  ~  
╰─$ free -o
free: invalid option -- 'o'

Usage:
 free [options]

Options:
 -b, --bytes         show output in bytes
 -k, --kilo          show output in kilobytes
 -m, --mega          show output in megabytes
 -g, --giga          show output in gigabytes
     --tera          show output in terabytes
 -h, --human         show human-readable output
     --si            use powers of 1000 not 1024
 -l, --lohi          show detailed low and high memory statistics
 -t, --total         show total for RAM + swap
 -s N, --seconds N   repeat printing every N seconds
 -c N, --count N     repeat printing N times, then exit
 -w, --wide          wide output

     --help     display this help and exit
 -V, --version  output version information and exit

For more details see free(1).

**Comment by zk-phi** [comment]
thanks, I got it, will be fixed soon.

**Comment by seemsindie** [comment]
Thanks, really nice of you :+1:
