### ISSUE TITLE
Graphs are invisible on dark color themes on OSX

### ISSUE THREAD

**Issue by pierre-lecocq** [zk-phi/symon#19]
(for the record, I'll try to manage it ASAP)

> I tested with some of light (dichromacy, light-blue, tango) and dark (deeper-blue, tango-dark, manoj-dark) themes loaded with `load-theme' and the problem seems common to dark themes. At least on Mac OS X.

I've tried solarized-dark and had no problems (color of sparklines inherits 'default face).
It may be an environment-dependent problem.

We can probably fix that by just adding :foreground and :background properties to sparklines.
can you try this ?

    (defadvice symon--make-sparkline (after fix activate)
      (setq ad-return-value
            (nconc ad-return-value '(:foreground "#ffffff"))))

**Comment by pierre-lecocq** [comment]
After some quick tests, it appears that the :foreground and :background properties of `image' are ignored on Mac OS X.

I tried on GNU/Linux (Debian), it worked, of course.

This is harsh.

**Comment by zk-phi** [comment]
hmm, how about using xpm images instead of xbm ?
if it works on OS X, adding option like `symon-sparkline-use-xpm` seems reasonable.

**Comment by pierre-lecocq** [comment]
I'll try this, @zk-phi. Gimme a little bit of time and I'll drop a line here.
Thanks

**Comment by zk-phi** [comment]
here's sparkline -> xpm converter function.

````
(defun sparkline->xpm (sparkline)
  (let ((data (plist-get (cdr sparkline) :data)))
    (print data)
    (with-temp-buffer
      (insert (format (concat "/* XPM */\n"
                              "static char * sparkline_xpm[] = {\n"
                              "\"%d %d 2 1\",\n"
                              "\"@ c %s\",\n"
                              "\". c none\"")
                      symon-sparkline-width
                      symon-sparkline-height
                      (face-foreground 'default)))
      (dotimes (ix (* symon-sparkline-width symon-sparkline-height))
        (when (zerop (mod ix symon-sparkline-width)) (insert ",\n\""))
        (insert (if (aref data ix) "@" "."))
        (when (zerop (mod (1+ ix) symon-sparkline-width)) (insert "\"")))
      (insert "};")
      `(image :type xpm :data ,(buffer-string) :ascent ,symon-sparkline-ascent
              :height ,symon-sparkline-height :width ,symon-sparkline-width))))
````

does this work fine ? `(insert-image (sparkline->xpm (symon--make-sparkline '(0 50 100))))`

**Comment by pierre-lecocq** [comment]
Yes it does !

**Comment by pierre-lecocq** [comment]
![screen shot 2015-02-12 at 18 40 43](https://cloud.githubusercontent.com/assets/235706/6173247/b5d92da0-b2e6-11e4-8484-c307676543b3.png)

**Comment by zk-phi** [comment]
wow! okay, I'll add the option soon.

**Comment by pierre-lecocq** [comment]
Thanks @zk-phi !

**Comment by zk-phi** [comment]
committed.

**Comment by pierre-lecocq** [comment]
Tested. And approved.
Works like a charm.

Thanks @zk-phi !
(sorry for the delay, I just finished my day of work. You were faster than me :))
