### ISSUE TITLE
Re-display symon only if there is no pending user input required

### ISSUE THREAD

**Issue by kaushalmodi** [zk-phi/symon#23]
I face this issue that symon aggressively re-displays even when emacs is wating for some input from a user in the echo area.

Example: When I try to quit emacs, I get this question in the echo area:

> This emacs session has clients; exit anyways? (y or n)

But if I wait for a second or two, symon displays come back and overwrites that question even before I respond with y or n. 

Do you consider this as a bug?
If not, can you provide an option so that symon display is held off as long as some user input is pending in the echo area?

**Comment by zk-phi** [comment]
Thanks for reporting.
symon does not redisplay while a minibuffer is active, but `y-or-n-p` actually does not use minibuffers to read user inputs so symon is redisplayed.
Now symon checks whether the cursor is in the echo area.
