### ISSUE TITLE
osx bogus numbers of memory

### ISSUE THREAD

**Issue by onemanstartup** [zk-phi/symon#26]
"Both usermem and physmem display useless values for systems over 2GB RAM. Both are probably bounded by a signed 32 bit integer " 

source - http://superuser.com/questions/197059/mac-os-x-sysctl-get-total-and-free-memory-size

It's better to use vm_stat as said in the source.

**Comment by zk-phi** [comment]
Thanks.
I unfortunately don't have a mac so I wonder if you (or someone else) can fix this. Probably all we need is to fix the command starting from line 472 in symon.el.

**Comment by RyanKung** [comment]
On my mac, the MEM is just shown as 'N/A', but I think the command is correct.

**Comment by RyanKung** [comment]
@onemanstartup @zk-phi Am I doing right? Please check the pull request

**Comment by onemanstartup** [comment]
@RyanKung is seems so. probably. I won't use symon anyway. So don't want to really

**Comment by zk-phi** [comment]
@RyanKung merged, thanks!
