### ISSUE TITLE
Changing symon-sparkline-width causes exception

### ISSUE THREAD

**Issue by dakrone** [zk-phi/symon#28]
When I tried to do `(setq symon-sparkline-width 100)`, I get the following when symon tries to display:

```
Error running timer ‘symon-display’: (args-out-of-range #&880"UUUUUUUUU\325
```

**Comment by zk-phi** [comment]
ooops, sparkline-types had to be regenerated after setting either `symon-sparkline-width` or `height`.
okay, I'll fix it later, thanks for reporting.

**Comment by zk-phi** [comment]
You can set the variable before loading symon to workaround this.
