### ISSUE TITLE
Use braille characters for graphics in terminal: ⢦⠓⡤⠎⠢

### ISSUE THREAD

**Issue by sshbio** [zk-phi/symon#29]
I made a basic (~300 SLOC) implementation of the [drawille] library (https://github.com/asciimoo/drawille) [in emacs lisp](https://github.com/sshbio/drawille)

As an example:

```
(drawille-draw-sparkline nil 2 0 3 2 0 1 1 3 2 1)
```

Would produce: `⢦⠓⡤⠎⠢`.

I can help to extract the relevant code from the library or to use it.

**Comment by zk-phi** [comment]
the library itself seems interesting, but the resolution is too low to render sparklines (in one line), IMO.

probably the library is useful when rendering images in multiple lines.

**Comment by sshbio** [comment]
Yes indeed...

4 dots per column, 5 states (0%, 25%, 50%, 75% or 100%) is not much.

Anyway, thank you for your answer!

Closing the issue...
