### ISSUE TITLE
Right-aligned + permanent display

### ISSUE THREAD

**Issue by Ambrevar** [zk-phi/symon#32]
Would it be possible to right-align the monitors in the mode-line?

This way it would make sense to add an option to leave the display permanently on.

To make it over the top, maybe symon could check when the text/cursor in the minibuffer reaches as far as the right side where it is displayed, in which case it would go into hiding.

What do you think?

**Comment by Ambrevar** [comment]
This would be particularly useful when minibuffer-greedy modes like flycheck and eldoc are on.

**Comment by zk-phi** [comment]
Thanks for posting :)
You mean displaying both messages (left side) and symon (right side) at the same time in the minibuffer line right ?
I think it's difficult since `message` function overwrites the whole minibuffer, and the only way I conceive is to redefine `message` itself (which seems unsafe) ...

**Comment by Ambrevar** [comment]
Overriding `message` would not be enough I suppose, what about `completing-read`, `yes-or-no-p`, etc.?

Random thoughts included using `minibuffer-setup-hook` and `minibuffer-exit-hook` to setup some sort of overlay, don't know if that's possible in Emacs...

**Comment by Ambrevar** [comment]
Basically setting the minibuffer in a special (minor?) mode where inserting characters does not alter the right side...
I am talking insane here? :p

**Comment by zk-phi** [comment]
It seems difficult or needs a lot of work...
I think another reasonable option to show messages and symon at the same time, is to use header-line (instead of minibuffer) to display monitors.

**Comment by Ambrevar** [comment]
Can you display a header-line across the whole frame independently of the windows?

**Comment by Ambrevar** [comment]
I've managed to set up dzen with EXWM (https://github.com/ch11ng/exwm/issues/281), so I won't be needed symon anymore.  Besides I might be asking for something impossible, thus I'm closing this now.
